- test/e2e/manifest.yaml
- test/e2e/storageclass-ci.yaml
The operator does not create a default storage class yet. Use a pre-defined one for CI.
In addition, update the manifest to vSphere
> Add vsphere StorageClass for our CI

- test/e2e/manifest.yaml
Snapshots and expansion are not supported by the CSI driver yet.
> Disable unsupported features

- assets/node.yaml
- pkg/generated/bindata.go
This pull request add `update strategy` field to the `daemon set` template. 
The commit sets the default value to `10 %`. 
fixes [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1947776) [vSphere csi driver operator] Should allow more nodes to be updated simultaneously for speeding up cluster upgrade
> Bug 1947776: fixed updateStrategy of the DaemonSet

- assets/vsphere_features_config.yaml
- pkg/generated/bindata.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953810
After these fixes, we no longer see issues we saw in - https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/9 and using storage policy works as expected.
> Bug 1953810: Update CSI driver configuration to the latest version

- assets/ca_configmap.yaml
- assets/controller.yaml
- assets/node.yaml
- pkg/operator/starter.go
The CA bundle may contain certificate used to connect to vCenter
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1969719, however, this is about the CSI driver, not vsphere-problem-detector and thus may not be necessary to be backported.
/assign @gnufied
> Add cluster CA bundle

- assets/rbac/csi_driver_binding.yaml
This is seen at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_vmware-vsphere-csi-driver/12/pull-ci-openshift-vmware-vsphere-csi-driver-master-e2e-vsphere-csi/1417212289345392640
> Driver in the node deals with ConfigMaps now

- assets/vsphere_features_config.yaml
- pkg/operator/starter.go
Since the driver is creating a bunch of v1beta1 CRDs, and that API is gone in OCP 4.9, we're disabling the deployment of the webhook and the CSI migration feature in the CSI driver. This should prevent the creation of CRD by the driver/syncer.
We'll revisit those once the upstream CRDs have been migrated to v1.
> Bug 1985847: Disable CSI migration and webhook deployment

- assets/webhook/deployment.yaml
The webhook is not currently deployed (see https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/34), but once we enabled it, it  should not run as __BestEffort__ qosClass.
> Bug 1985852: Set CPU and memory requests for webhook

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/vmware.go
Currently, every time the operator syncs a new session is established.
This patch changes the current behavior by closing the session after it was used.
This should help improving the current situation, however we also need to investigate the upstream CSI driver which apparently is leaking sessions as well.
> Bug 2009859: Close connection to vCenter API

- pkg/operator/storageclasscontroller/storageclasscontroller.go
The intention of this PR is to backport a fix to close stale connections which was implemented in #50 and #47 to 4.8.  There are structural differences in pkg/operator/storageclasscontroller/vmware.go which prevent a cherrypick and as such this PR was created.  As is done in prior PRs on this issue, logout is called on the vim25.Client instance which results in the session being logged out and idle connections being closed.
> [release-4.8] Bug 2021620: Close connection to vCenter API

- pkg/operator/vclib/connection.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2039406
Note to reviewers: While I tested this PR with real cluster and did not see any problems, for me - currently there is no way to measure rest session count, so I don't really know if it *really* works. I do know that it does not break.
> Bug 2039406: Also logout from restclient

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Previously we did not degrade or mark cluster as unpgradeable when we can't connect to vcenter.
This PR changes that behaviour and *always* degrades the cluster if we previously installed the CSI driver and one or more of CSI driver pre-requisties is unsatisfied. This is necessary because CSI driver will be crash looping or being non-functional anyway when this happens. 
xref https://bugzilla.redhat.com/show_bug.cgi?id=2040880
> Bug 2040880: Degrade the OCP cluster if driver is found

- pkg/operator/vspherecontroller/vsphere_environment_checker.go
- pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=2043651
Appears to be working correctly:
```
E0121 16:20:26.321957       1 vsphere_environment_checker.go:82] marking cluster as un-upgradeable: node co8-tkxz9-worker-znq5f has hardware version vmx-13, which is below the minimum required version 15
I0121 16:20:26.321962       1 vspherecontroller.go:229] Scheduled the next check in 2m0.413801699s
W0121 16:20:26.321987       1 vspherecontroller.go:423] Marking cluster un-upgradeable because node co8-tkxz9-worker-znq5f has hardware version vmx-13, which is below the minimum required version 15
I0121 16:22:26.860525       1 vmware.go:273] Found existing profile with same name: openshift-storage-policy-co8-tkxz9
E0121 16:22:26.864714       1 vsphere_environment_checker.go:82] marking cluster …
```
> Bug 2043651: Fix bug with nextCheck not being changed correctly

- pkg/operator/vspherecontroller/vspherecontroller.go
If operator creates a metric indicating error the metric is never
removed and reported even if user resolved the issue.
For example setting incorrect password for vsphere connection degrades
the operator state and emits a metric when periodic sync is performed.
If user then corrects the password and vsphere client succeeds this
metric is persisted.
This patch should ensure we reset the metric if we don't detect any
known negative state (defined in blockUpgradeOrDegradeCluster())
> Bug 2059791: [vSphere CSI driver Operator] didn't update 'vsphere_csi_driver_error' metric value when fixed the error manually

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/storageclasscontroller_test.go
- pkg/operator/testlib/storageclass1.yaml
- pkg/operator/testlib/storageclass2.yaml
- pkg/operator/testlib/testlib.go
- pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Adding basic storage class controller tests as we were missing coverage in this area completely.
The intention is to have tests where we can mock storage policy API, and control it's success/failure and also to have the possibility to insert different storage class objects into the tests. Not sure if we ever need the latter though. Initially I thought we could test by re-applying storage classes but the fake kube api does not provide any validation. So for example if we try to change immutable field by applying a different storage class, the fake api does not prevent it.
However I still think it's a valid test and having the option to use different SC objects for tests could be useful in the future.
> add storageclass controller tests

- assets/controller.yaml
- assets/service.yaml
- assets/servicemonitor.yaml
The CSI driver does not have configurable port for the metrics and due to `hostNetwork` they will be exposed on the node.
I opened https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1720 upstream.
> Bug 2076637: Scrape CSI driver + syncer metrics

- assets/controller.yaml
- assets/service.yaml
- assets/servicemonitor.yaml
- assets/volumesnapshotclass.yaml
- assets/vsphere_features_config.yaml
- pkg/operator/vspherecontroller/driver_starter.go
- test/e2e/manifest.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2071021
Tests appear to be working:
```
76 pass, 164 skip (7m23s)
Storage Capabilities (guaranteed only on full CSI test suite with 0 fails)
==========================================================================
Driver short name:                         
Driver name:                               csi.vsphere.vmware.com
Storage class:                             
Supported OpenShift / CSI features:
Persistent volumes:                      true
Raw block mode:                          true
FSGroup:                                 true
Executable files on a volume:            true
Volume snapshots:                        true
Volume cloning:                          false
Use volume from multiple pods on a node: false
ReadWriteMany …
```
> Bug 2071021: Enable snapshot support

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/checks/check_existing_driver.go
- pkg/operator/vspherecontroller/vsphere_environment_checker.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
The first commit refactors two bools into enum, to be able to add a third possible outcome of a failed check.
The second commit then blocks CSI driver installation when the driver is already installed and it's not the OCP one. The operator looks "Available: true" + "Upgradeable: true", however, the Upgradeable condition has a message `found existing unsupported csi.vsphere.vmware.com driver`.
WIP:
* Add unit test.
* Think about useful alert.
> Bug 2089419: Don't block upgrades when another CSI driver is found

- assets/webhook/deployment.yaml
- assets/webhook/pdb.yaml
- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/webhook_controller.go
There should be always at least one replica of the webhook always running to make sure API requests are processed + the operator does not go `Available: "false"`.
* Add PodDisruptionBudget with 1 replica.
* Use `MaxUnavailable: 1`.
* Tune nr. of replicas to `1` on single-node cluster, `2` everywhere else.
* Run the webhook on regular nodes in hypershift (masters are not there)
All this code is already used in other CSI driver Deployments.
> Bug 2081557: Run at least one replica of Webhook

- pkg/operator/vspherecontroller/vspherecontroller.go
https://bugzilla.redhat.com/show_bug.cgi?id=2094783
This fix just moves the storage class sync below the point at which we check `degradedOrBlockedFromUpgrades` so that we do not create the storage class if the upgrade is blocked.
/hold for testing
/cc @openshift/storage
> Bug 2094783: storageclass should not be created for unsupported vsphere version

- assets/controller.yaml
- assets/node.yaml
- assets/webhook/deployment.yaml
- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/webhook_controller.go
When the operand log level is Debug or higher, then add `LOGGER_LEVEL=DEVELOPMENT` to get detailed logs of the CSI driver.
It's really annoying to set the env. var manually if I need the logs.
> STOR-963: Add LOGGER_LEVEL env. var on debug log level

- pkg/operator/vspherecontroller/driver_starter.go
There really shouldn't be more than one set of credentials in OCP secrets because CSI driver can't support more than one vcenter anyways.
For now lets warn the users, so as it is easier to debug. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2108473
> Bug 2108473: Warn if multiple credentials exists in secrets

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- pkg/operator/vspherecontroller/checks/check_vcenter.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Block OCP 4.12 upgrade to 4.13 when:
* vCenter or any ESXi host is older than v7.0.2.
* or community CSI driver is installed.
I had to rework the operator a bit, because I needed to distinguish "Block upgrade if the driver is not installed or degrade the cluster if it is installed" from "Just block upgrade", see the first commit.
This implements both https://issues.redhat.com/browse/STOR-951 and https://issues.redhat.com/browse/STOR-794
> STOR-794: Block upgrade when vSphere is < 7.0.2

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Because all cases where CSI driver installation is blocked should also block upgradeability of the cluster.
In addition, emit both `install_blocked` and `upgrade_blocked` metrics in this case.
Since Upgradeable condition is set in several places, return cluster upgradeability from `blockUpgradeOrDegradeCluster()` function.
> OCPBUGS-940: Rework "BlockDriverInstall" to "BlockUpgradeDriverInstall"

- go.mod
- go.sum
- pkg/operator/starter.go
- pkg/operator/utils/apiclients.go
- pkg/operator/vspherecontroller/driver_starter.go
- vendor/github.com/openshift/library-go/pkg/config/serving/server.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/modules.txt
When the cluster-csi-snapshot-controller-operator is not deployed, (through the CSISnapshot capability) the VolumeSnapshotClass CRD is not created at all.
In that case, it doesn't make sense to deploy the CR, otherwise the operator gets degraded.
>  OCPBUGS-1904: Only deploy VolumeSnapshotClass when CRD exists

- assets/controller.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
- vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-2083
Testing changes for https://github.com/openshift/library-go/pull/1413
The library-go change needs to be merged first and re-vendored in this PR.
/cc @openshift/storage
> OCPBUGS-2083: set TLS cipher suites in Kube RBAC sidecars

- assets/controller.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
- vendor/modules.txt
/hold for https://github.com/openshift/library-go/pull/1414
I need to bump library-go once that merges.
> [release-4.12] OCPBUGS-3281: set TLS cipher suites in Kube RBAC sidecars

- test/e2e/manifest.yaml
This CSI driver actually [does not support multiple PVs with the same VolumeHandle](https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1913). It is the reason why multiplePVsSameID capability was introduced.
> Bug 2106736: Fix multiplePVsSameID value in tests

- pkg/operator/utils/metric.go
- pkg/operator/utils/topology.go
- pkg/operator/utils/topology_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- `vsphere_topology_tags_total` reports how many tag categories are configured for the CSI driver topology. It has label "`source`" with two values:
- "`clustercsidriver`" - nr. of topology categories configured in the  ClusterCSIDriver instance
- "`infrastructure`" - always 2, if infrastructure describes any topology (openshift-region and openshift-zone categories are used by OCP in this case), 0 otherwise.
- `vsphere_infrastructure_failure_domains_total` - reports total nr. of configured vSphere failure domains in the Infrastructure instance. Has label "`scope`" with values:
- regions
- zones
- vcenters
- datacenters
- datastores
- failure_domains
> STOR-1145: Add metric for topology

- pkg/operator/utils/topology.go
- pkg/operator/utils/topology_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
Fixes https://issues.redhat.com/browse/OCPBUGS-7482
> OCPBUGS-7482: Do not enable topology features if only one failure-domains is defined

- assets/controller.yaml
- assets/node.yaml
- assets/webhook/deployment.yaml
To support the workload partitioning we need to add the required annotations (openshift/enhancements#703).
> OCPBUGS-8683: Add management workloads annotations

- pkg/operator/utils/metric.go
- pkg/operator/utils/topology.go
- pkg/operator/utils/topology_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
Based on https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/145
Add `vsphere_csi_migration` metric that shows value of `storage.spec.vsphereStorageDriver` as a metric.
> OCPBUGS-11294: Add CSI migration metric

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/storageclasscontroller_test.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Also remove targetconfigController
Fixes https://issues.redhat.com/browse/OCPBUGS-12712
> OCPBUGS-12712: Add backoff for successful storage policy creations

- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/webhook_controller.go
Adding WithSecretHashAnnotationHook() for vmware-vsphere-csi-driver-controller-metrics-serving-cert ensures that new annotation is published in vmware-vsphere-csi-driver-controller deployment. This, in turn, leads to controller pods restart.
Similarly, adding WithSecretHashAnnotationHook() for vmware-vsphere-csi-driver-webhook-secret ensures that new annotation is published in vmware-vsphere-csi-driver-webhook deployment. This, in turn, leads to webhook pods restart.
> STOR-1304: Restart controller pods if metrics serving cert or webhook secret changed

- assets/controller.yaml
To allow use of EgressIP with controller `hostNetwork` must be disabled for controller. 
Upstream does not use `hostNetwork: true` for controller deployment: https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/fcfcc25004ed6992ef05558cf123159a96361245/manifests/vanilla/vsphere-csi-driver.yaml#L191
I've tested if changing this option does not break liveness probes and metrics (with OVN networking) and did not find any issues: 
1) Verify hostNetwork is not used:
```
oc -n openshift-cluster-csi-drivers get deployment/vmware-vsphere-csi-driver-controller -o yaml | grep hostNetwork
```
2) Verify liveness probe:
```
$ oc -n openshift-cluster-csi-drivers get pod | grep controller
vmware-vsphere-csi-driver-controller-677856cf46-7cnzc   13/13   Running   0          16m …
```
> OCPBUGS-13084: disable controller hostNetwork

- pkg/operator/starter.go
- pkg/operator/testlib/testlib.go
- pkg/operator/vspherecontroller/checks/api_interface.go
- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/checks/check_error_test.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- pkg/operator/vspherecontroller/checks/check_patched_vcenter.go
- pkg/operator/vspherecontroller/checks/check_patched_vcenter_test.go
- pkg/operator/vspherecontroller/vcsim_framework.go
- pkg/operator/vspherecontroller/vsphere_environment_checker.go
- pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Fixes https://issues.redhat.com/browse/OCPBUGS-18131
> OCPBUGS-18131: Block upgrade to 4.13 via  admin ack

- pkg/operator/vspherecontroller/vspherecontroller.go
Fixes https://issues.redhat.com/browse/OCPBUGS-21826
> OCPBUGS-21826: Warn when managment state is set to values other than Managed

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
When CSI driver installation is blocked, e.g. because upstream CSI driver is installed, add a dummy `Progressing` condition 
to ClusterCSIDriver. Because without any *Progressing condition, CSO will default to `Progressing=True` and the whole storage will be `Progressing=True` forever.
> OCPBUGS-23342: Add dummy Progressing condition on blocked driver install

- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
When the operator does not start the CSI driver, e.g. because it does not have credentials to vSphere, mark the operator as `Disabled: true`.
cluster-storage-operator will then report the whole storage as `Available: true`, `Progressing: false` with some message about the vSphere error.
Note that `Upgradeable` and `Degraded` conditions are still propagated from ClusterCSIDriver to CSO, regardless of `Disabled: true`.
Also remove `VMwareVSphereControllerAvailable` condition, it would create `Available: true` before CSI controllers had a chance to report their `Available: false`.
> OCPBUGS-27159: Mark the operator as Disabled on connection error 

- assets/node.yaml
This will help from crashing the container if someone runs `oc debug` accidently against it or something.
Fixes https://issues.redhat.com/browse/OCPBUGS-26924
> OCPBUGS-26924: Enable healthcheck for node-registrar containerPort

- assets/csi_cloud_config.ini
- pkg/operator/vspherecontroller/config_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
The CSI driver uses the `gcfg` library to read the INI configuration file generated by this operator. However, that library will truncate passwords containing inline comments (like commas).
To avoid that, we make sure that the INI file we render contains credentials values wrapped in double quotes.
> OCPBUGS-37201: Make sure credentials are wrapped in double quotes

- pkg/operator/vspherecontroller/driver_starter.go
fixes https://issues.redhat.com/browse/OCPBUGS-37455
> STOR-1593: Disable toplogy feature explicitly

- go.mod
- pkg/operator/driverfeaturescontroller.go
- pkg/operator/driverfeaturescontroller_test.go
CSI migration is not supported in clusters with multiple vCenters.
In addition, add some unit tests for `improved-volume-topology` feature.
`migration-datastore-url` is added/removed to/from the ini file based on nr. vCenters already:
https://github.com/openshift/vmware-vsphere-csi-driver-operator/blob/3358d00cf279c8abd53ae2267374ef66ed505356/pkg/operator/vspherecontroller/vspherecontroller.go#L732-L734
> OCPBUGS-37772: Disable CSI migration in multi-vCenter cluster

- test/e2e/ocp-tests.yaml
The LUN stress test finished under 10 minutes few times, adding 20 minutes as a buffer.
> STOR-1819: Add manifest with OCP specific test config

- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/vspherecontroller.go
Restart CSI driver controller Deployment when vsphere-csi-config-secret changes. And make a constant with the secret name.
The driver itself does not read vmware-vsphere-cloud-credentials, it's ready by the operator and translated into vsphere-csi-config-secret. So remove its secret hash from the controller.
> OCPBUGS-38272: Restart CSI driver controller pod on config change

- pkg/operator/testlib/testlib.go
- pkg/operator/testlib/vcsim_framework.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Convert the legacy ini file config to infrastructure not only when `VSphere.VCenters` is empty, but also when VSphere itself is nil.
This happens when the infrastructure was created by OCP 4.10 and older.
And make sure the operator does not overwrite the infrastructure in informer cache.
> OCPBUGS-43417: Fix panic on nil infrastructure Spec.PlatformSpec.VSphere

- pkg/operator/storageclasscontroller/multivcenterstorageclasscontroller.go
- pkg/operator/storageclasscontroller/storageclasscontroller.go
The patch fixes e2e-vsphere-operator-test. It failed before because vmware-vsphere-csi-driver-operator attempted to call non-existent SyncRemove method of MultiVCenterStorageClassController:
```
W1210 21:52:45.753900       1 vspherecontroller.go:183] VMwareVSphereController: ManagementState is Removed, skipping
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc021d18378 stack=[0xc021d18000, 0xc041d18000]
fatal error: stack overflow
...
github.com/openshift/vmware-vsphere-csi-driver-operator/pkg/operator/storageclasscontroller.(*MultiVCenterStorageClassController).SyncRemove(0xc000cc65a0?, {0x3d138c8?, 0xc000af5e50?})
```
(see full logs [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_vmware-vsphere-csi-driver-op …
> OCPBUGS-45563: Move SyncRemove to AbstractStorageClass

- pkg/operator/testlib/vcsim_framework.go
- pkg/operator/vspherecontroller/checks/api_interface.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
The operaor needs to check only linux nodes. The customer reported that checks for Windows nodes fail because vspherecontroller unable to find VM by UUID.
> OCPBUGS-46089: List only linux nodes

- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
VMWare/Broadcom docs requre double backslash in the username:
> You must specify the username along with the domain name.
> For example, user = "userName@domainName" or user = "domainName\\\\username".
(https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-BFF39F1D-F70A-4360-ABC9-85BDAFBE8864.html)
> OCPBUGS-46574: Escape backslash in vCenter username

- assets/controller.yaml
Cherry-pick upstream [PR#3015](https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/3015) for https://issues.redhat.com/browse/OCPBUGS-49406.
> OCPBUGS-49406: Set reconcile-sync to 10 minute for ListVolume

- pkg/operator/vclib/connection.go
- pkg/operator/vspherecontroller/vspherecontroller.go
When address of vcenter was set incorrectly, the code would throw runtime error, this PR fixes it.
> OCPBUGS-43273: fix panic when vcenter address is incorrect

- test/e2e/manifest-topology.yaml
When adding the multi-zone/multi-vcenter CI, some cases will check if there are at least 2 nodes in the same zone and need the topology Capability. 
The other profile that doesn't have the zonal configuration will still need the previous manifest. (The topology key is null)
> STOR-2245: add manifest-topology.yaml for topology related feature and test
