- Dockerfile.openshift
- cmd/vmware-vsphere-csi-driver-operator/main.go
> Add missing ./cmd directory

- Dockerfile.test
To have an image with test/e2e/*.yaml available in CI jobs.
> Add Dockerfile.test

- pkg/operator/starter.go
- pkg/operator/storageclasscontroller/storageclasscontroller.go
> Resync controller when user changes StorageClass

- assets/controller.yaml
- assets/node.yaml
- pkg/generated/bindata.go
> Fix image references

- assets/csidriver.yaml
- pkg/generated/bindata.go
- pkg/operator/starter.go
Already with annotation `csi.openshift.io/managed`.
> Add CSIDriver instance

- assets/controller.yaml
- manifests/08_deployment.yaml
- pkg/generated/bindata.go
- pkg/operator/starter.go
Sync vsphere syncer image from CSO injected environment variables.
> add vsphere syncer

- assets/storageclass.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1989077
> Bug 1989077: Fix storageclass churn

- OWNERS
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
- vendor/modules.txt
https://bugzilla.redhat.com/show_bug.cgi?id=1984942
Bumping library-go to bring the fix in.
> Bug 1984942: ApplyClusterRoleBinding triggers boundsError when adding new subject

- pkg/operator/starter.go
In #35 I forgot to call the function hook that effectively sets the number of replicas of the CSI Controller Deployment.
> Bug 1948090: Fix number of replicas

- assets/controller.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1990146
> Bug 1990146: some controllers missing livenessProbe

- test/e2e/manifest.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1948607
> Bug 1948607: Enable volume expansion tests

- assets/controller.yaml
- pkg/dependencymagnet/dependencymagnet.go
Add resources for syncer - Fixeshttps://bugzilla.redhat.com/show_bug.cgi?id=2008207
> Bug 2008207: Add resources for syncer

- pkg/operator/vspherecontroller/vspherecontroller_test.go
Add tests for existing CSI driver and make sure cluster is marked as un-upgradeable.
> Add tests for existing CSI driver

- pkg/operator/vspherecontroller/checks/check_existing_driver.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2034624
> Bug 2034624: change logged message when existing csi driver found

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/vmware.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2034287
> Bug 2034287: Do not block upgrades if storageclass resync fails because of vcenter

- assets/storageclass.yaml
Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=2034622
> Bug 2034622: Enable volume expansion by default in CSI driver

- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2040880
> Bug 2040880: Mark cluster upgradeable to be unknown when we can't connect to vcenter

- pkg/operator/storageclasscontroller/storageclasscontroller.go
Only degrade if storage class creation fails because of API error
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2047779
> Bug 2047779: Never degrade cluster on storage policy syncResult

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Fixes https://issues.redhat.com/browse/OCPBUGS-5472
> OCPBUGS-5472: Fix sc creation on resync

- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Fixes https://issues.redhat.com/browse/OCPBUGS-5507
> OCPBUGS-5507: Fix sc creation if it is deleted

- go.mod
- go.sum
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- pkg/operator/testlib/multiple_dc.ini
- pkg/operator/testlib/multiple_vc.ini
- pkg/operator/testlib/simple_config.ini
- pkg/operator/testlib/testlib.go
- pkg/operator/utils/constants.go
- pkg/operator/utils/topology.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- vendor/gopkg.in/ini.v1/.gitignore
- vendor/gopkg.in/ini.v1/.travis.yml
- vendor/gopkg.in/ini.v1/LICENSE
- vendor/gopkg.in/ini.v1/Makefile
- vendor/gopkg.in/ini.v1/README.md
- vendor/gopkg.in/ini.v1/data_source.go
- vendor/gopkg.in/ini.v1/deprecated.go
- vendor/gopkg.in/ini.v1/error.go
- vendor/gopkg.in/ini.v1/file.go
- vendor/gopkg.in/ini.v1/helper.go
- vendor/gopkg.in/ini.v1/ini.go
- vendor/gopkg.in/ini.v1/key.go
- vendor/gopkg.in/ini.v1/parser.go
- vendor/gopkg.in/ini.v1/section.go
- vendor/gopkg.in/ini.v1/struct.go
- vendor/modules.txt
Fixes https://issues.redhat.com/browse/OCPBUGS-5790
This is basically a manual cherry-pick of https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/123 because automatic cherry-pick was throwing tons of conflicts.
> OCPBUGS-5790: Allow cluster to be upgraded even if using multiple datacenters

- go.mod
- go.sum
- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/storageclasscontroller_test.go
- pkg/operator/testlib/testlib.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
- vendor/modules.txt
https://issues.redhat.com/browse/STOR-947
Marking this WIP until https://github.com/openshift/library-go/pull/1441 merges.
/cc @openshift/storage
> STOR-947: support disabling default StorageClass via ClusterCSIDriver

- go.mod
- go.sum
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- pkg/operator/testlib/multiple_dc.ini
- pkg/operator/testlib/multiple_vc.ini
- pkg/operator/testlib/simple_config.ini
- pkg/operator/testlib/testlib.go
- pkg/operator/utils/constants.go
- pkg/operator/utils/topology.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- vendor/gopkg.in/ini.v1/.gitignore
- vendor/gopkg.in/ini.v1/.travis.yml
- vendor/gopkg.in/ini.v1/LICENSE
- vendor/gopkg.in/ini.v1/Makefile
- vendor/gopkg.in/ini.v1/README.md
- vendor/gopkg.in/ini.v1/data_source.go
- vendor/gopkg.in/ini.v1/deprecated.go
- vendor/gopkg.in/ini.v1/error.go
- vendor/gopkg.in/ini.v1/file.go
- vendor/gopkg.in/ini.v1/helper.go
- vendor/gopkg.in/ini.v1/ini.go
- vendor/gopkg.in/ini.v1/key.go
- vendor/gopkg.in/ini.v1/parser.go
- vendor/gopkg.in/ini.v1/section.go
- vendor/gopkg.in/ini.v1/struct.go
- vendor/modules.txt
Fixes https://issues.redhat.com/browse/OCPBUGS-5895
> OCPBUGS-5895: Backport multi dc support 410

- assets/storageclass.yaml
- go.mod
- go.sum
- pkg/operator/storageclasscontroller/storageclasscontroller.go
- pkg/operator/storageclasscontroller/storageclasscontroller_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- vendor/github.com/openshift/library-go/pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
- vendor/modules.txt
> STOR-1128: Change the default SC to the CSI one

- assets/vsphere_features_config.yaml
https://issues.redhat.com/browse/STOR-1120
> STOR-1120: Add csi idempotency flags

- assets/controller.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-7899
> OCPBUGS-7899: Bump sidecar timeouts for vsphere

- assets/vsphere_features_config.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-13386
> OCPBUGS-13386: Use csinode id feature

- assets/vsphere_features_config.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-14581
> OCPBUGS-14581: Enable Windows supports

- pkg/operator/starter.go
- pkg/operator/testlib/testlib.go
- pkg/operator/testlib/vcsim_framework.go
- pkg/operator/vspherecontroller/checks/api_interface.go
- pkg/operator/vspherecontroller/checks/check_error.go
- pkg/operator/vspherecontroller/checks/check_error_test.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- pkg/operator/vspherecontroller/checks/check_patched_vcenter.go
- pkg/operator/vspherecontroller/checks/check_patched_vcenter_test.go
- pkg/operator/vspherecontroller/vsphere_environment_checker.go
- pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
Fixes https://issues.redhat.com/browse/OCPBUGS-18132
> OCPBUGS-18132: Block 4.14 upgrades with admin ack

- assets/webhook/deployment.yaml
> OCPBUGS-22385:disable http/2 server support in webhook

- pkg/operator/vspherecontroller/driver_starter.go
Fixes https://issues.redhat.com/browse/OCPBUGS-20481
> OCPBUGS-20481: Fix vsphere csi controller pods from getting constantly restarted

- pkg/operator/testlib/testlib.go
- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/driver_starter_test.go
> OCPBUGS-20481: Implement fallback to configmap when Infra object does not have vCenter

- assets/vsphere_features_config.yaml
Reverts openshift/vmware-vsphere-csi-driver-operator#192
> OCPBUGS-24716:  Enable new features to prevent CSI driver from crash looping (revert OCPBUGS-23970)

- pkg/operator/vspherecontroller/vsphere_environment_checker.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
> OCPBUGS-24421: Rerun checks on reconnect

- assets/webhook/deployment.yaml
Addressing https://github.com/openshift/origin/pull/28777/files#r1592893974 
/cc @deads2k @jsafrane
> OCPBUGS-28230: enforce termination message policy on all platform pods

- assets/controller.yaml
- assets/csi_cloud_config.ini
- assets/vsphere_cloud_config_secret.yaml
- pkg/operator/starter.go
- pkg/operator/vspherecontroller/driver_starter.go
- pkg/operator/vspherecontroller/vspherecontroller.go
- pkg/operator/vspherecontroller/vspherecontroller_test.go
> STOR-1290: don't pass credentials via environment variables in vSphere

- pkg/operator/vspherecontroller/config.go
- pkg/operator/vspherecontroller/config_test.go
- pkg/operator/vspherecontroller/vspherecontroller.go
> OCPBUGS-37201: Ignore comment symbols when reading the ini file

- cmd/cns-migration/main.go
- pkg/cnsmigration/migrator.go
fixes https://issues.redhat.com/browse/OCPBUGS-38026
> OCPBUGS-38026: Implement minor quality of life improvements.

- README.md
The PR updates README.md:
- delete webhook deployment
- export OPERATOR_NAME
> NO-JIRA: Update "Quick start" section of README

- pkg/cnsmigration/migrator.go
- pkg/operator/utils/version_check.go
- pkg/operator/utils/version_check_test.go
- pkg/operator/vclib/connection.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
- pkg/operator/vspherecontroller/checks/check_vcenter.go
Fixes https://issues.redhat.com/browse/OCPBUGS-41532?filter=12399251
> OCPBUGS-41532: Add check for vCenter version

- third_party/cloud-provider-vsphere/pkg/common/config/config.go
- third_party/cloud-provider-vsphere/pkg/common/config/config_yaml.go
Fixes https://issues.redhat.com/browse/OCPBUGS-38368
> OCPBUGS-38368: Fix the config loading warning

- pkg/operator/testlib/vcsim_framework.go
- pkg/operator/vspherecontroller/checks/api_interface.go
- pkg/operator/vspherecontroller/checks/check_nodes.go
This is a manual cherry-pick of https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/285
/assign mpatlasov
> [release-4.16] OCPBUGS-49862: List only linux nodes

- README.md
- pkg/operator/vclib/connection.go
> OCPBUGS-48103: Update master to main

- assets/controller.yaml
- assets/webhook/deployment.yaml
https://issues.redhat.com//browse/STOR-2330
This PR subscribes vSphere CSI driver controller and webhook pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579.
> STOR-2330: Add labels to subscribe vSphere CSI driver controller and webhook to NPs
